stages:
  - build
  - test
  - publish

variables: &default_variables
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: "fast"
  CACHE_COMPRESSION_LEVEL: "fast"
  NPM_CONFIG_LOGLEVEL: verbose

image: registry-gitlab.ganchrow.com/ganchrow/gsdockerfiles:nodejs20-dev

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
  artifacts:
    when: always
    paths:
      - node_modules/
      - target/
      - lib/

test:
  stage: test
  script:
    - ./scripts/test.sh
  dependencies:
    - build

publish-new-patch:
  variables:
    <<: *default_variables
    UPDATE_TYPE: patch
  extends: .update-version

publish-new-minor:
  variables:
    <<: *default_variables
    UPDATE_TYPE: minor
  extends: .update-version

publish-new-major:
  variables:
    <<: *default_variables
    UPDATE_TYPE: major
  extends: .update-version

.update-version:
  stage: publish
  before_script:
    - git remote set-url origin https://oauth2:$GITLAB_PUBLISH_TOKEN@gitlab.ganchrow.com/ganchrow/gs-utils.git
    - git config --global user.email "${GIT_USER_EMAIL:-$GITLAB_USER_EMAIL}"
    - git config --global user.name "${GIT_USER_NAME:-$GITLAB_USER_NAME}"
    - git checkout $CI_COMMIT_REF_NAME
  script:
    - ls -la lib/
    - VERSION=$(npm version "${UPDATE_TYPE}" -no-git-tag-version --force | cut -c 1-)
    - echo $VERSION
    - npm publish --ignore-scripts
    - git add .
    - git commit -m "[skip ci] - new version deploy $VERSION"
    - git tag -a $VERSION -m "$VERSION"
    - git push origin master --follow-tags
  only:
    - master
    - tags
  dependencies:
    - build
  when: manual
