#!/usr/bin/env node

/* Copyright © 2017 Ganchrow Scientific, SA all rights reserved */
'use strict';

let path = require('path');

let packagePath = path.resolve(process.argv[2]);
let propertyName = process.argv[3];

let value = require(`${packagePath}/package.json`)[propertyName];

console.log(value);
